<?php

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function caldo_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#caldo":
      $output = '<p>'.  t("La ayuda del proyecto =D") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implementación de hook_menu().
 * @return menú en forma de arreglo php
*/
function caldo_menu(){
/*
  $items['caldo'] = array(
    'title' => 'Este es un menu', // el título
    'access arguments' => array(1), // todos tienen acceso a ver este menú
    'page callback' => 'caldo_vista1',  // la función a llamar
    'file' => 'vistas.php'
  );
  
  return $items;
*/
}
